// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy0m-3ggIBGf0HNKzidw2Y_h61XW9oguA',
    appId: '1:316973893429:web:0b3616af02a315f2c6ee7c',
    messagingSenderId: '316973893429',
    projectId: 'pet-peeves-ys',
    authDomain: 'pet-peeves-ys.firebaseapp.com',
    storageBucket: 'pet-peeves-ys.firebasestorage.app',
    measurementId: 'G-1NRLS7JW4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtHpU_v5hM6hgK13htTnzDq9RAS2coTkA',
    appId: '1:316973893429:android:dc80a9ef92e1b964c6ee7c',
    messagingSenderId: '316973893429',
    projectId: 'pet-peeves-ys',
    storageBucket: 'pet-peeves-ys.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi91uM-zXviKTkmG08KyYNG5MnaGWk6zA',
    appId: '1:316973893429:ios:a2a0c874fb40277dc6ee7c',
    messagingSenderId: '316973893429',
    projectId: 'pet-peeves-ys',
    storageBucket: 'pet-peeves-ys.firebasestorage.app',
    iosClientId: '316973893429-8q1uuub4pci6c8mk0v09qal74an2t9pl.apps.googleusercontent.com',
    iosBundleId: 'com.example.petPeeves',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi91uM-zXviKTkmG08KyYNG5MnaGWk6zA',
    appId: '1:316973893429:ios:a2a0c874fb40277dc6ee7c',
    messagingSenderId: '316973893429',
    projectId: 'pet-peeves-ys',
    storageBucket: 'pet-peeves-ys.firebasestorage.app',
    iosClientId: '316973893429-8q1uuub4pci6c8mk0v09qal74an2t9pl.apps.googleusercontent.com',
    iosBundleId: 'com.example.petPeeves',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy0m-3ggIBGf0HNKzidw2Y_h61XW9oguA',
    appId: '1:316973893429:web:6492da3f297d5f84c6ee7c',
    messagingSenderId: '316973893429',
    projectId: 'pet-peeves-ys',
    authDomain: 'pet-peeves-ys.firebaseapp.com',
    storageBucket: 'pet-peeves-ys.firebasestorage.app',
    measurementId: 'G-SV1NX5Q4CB',
  );
}
